
[formatter.haskell]
command = "fourmolu"
options = ["-i"]
includes = [ "*.hs" ]
excludes = []

[formatter.cabal-fmt]
command = "cabal-fmt"
excludes = []
includes = ["*.cabal"]
options = ["-i"]

[formatter.alejandra]
command = "alejandra"
excludes = []
includes = ["*.nix"]
options = []
